version: '3.1'
services:
  mongo:
   build: .
   container_name: mongodb
   restart: always
   environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27017
   ports:
    - '27017:27017'
    